// <auto-generated>
// Rewired Constants
// This list was generated on 7/28/2019 12:33:19 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Game
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Game", friendlyName = "MoveHorizontal")]
        public const int Game_MoveHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Game", friendlyName = "MoveVertical")]
        public const int Game_MoveVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Game", friendlyName = "Attack_1")]
        public const int Game_Attack_1 = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Game", friendlyName = "Attack_2")]
        public const int Game_Attack_2 = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Game", friendlyName = "Action")]
        public const int Game_Action = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Game", friendlyName = "Dash")]
        public const int Game_Dash = 11;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Submit")]
        public const int UI_Submit = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int UI_Cancel = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Up")]
        public const int UI_Up = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Down")]
        public const int UI_Down = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Left")]
        public const int UI_Left = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Right")]
        public const int UI_Right = 7;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int Game = 1;
        public const int UI = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
